name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build and test
      uses: devcontainers/ci@v0.2
      with:
        imageName: ghcr.io/example/example-devcontainer
        cacheFrom: ghcr.io/example/example-devcontainer
        push: never
        runCmd: ./gradlew check --info --console=plain
